using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using BotSpiel.Data;
using BotSpiel.DataAccess.Data;
using BotSpiel.Models;
using BotSpiel.DataAccess.Models;
using BotSpiel.DataAccess.Repositories;
using BotSpiel.Services;
//Custom Code Start | Added Code Block 
using BotSpiel.DataAccess.Utilities;
using FluentValidation;
//Custom Code End

namespace BotSpiel
{
    public static class BotSpielModule
    {
        public static void LoadModule(IServiceCollection services, IConfiguration Configuration)
        {
			services.AddDbContext<AisleFaceStorageTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<AssemblyModuleGridsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<BaySequenceTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<BusinessPartnerTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<CarrierTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<CommunicationMediumsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<ContactFunctionsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<CurrencyTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<DateTimePeriodFormatsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<DateTimePeriodFunctionsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<DocumentMessageTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<ExecutionModuleGridsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<FoundationModuleGridsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<HandlingUnitTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InboundModuleGridsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InboundOrderTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InventoryModuleGridsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InventoryStatesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InventoryUnitTransactionContextsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<LocationFunctionsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<LogicalOrientationsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MaterialTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MeasurementUnitsOfDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MessageFunctionsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MessageResponseTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MonetaryAmountTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MoveQueueContextsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MoveQueueTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<NetworkModuleGridsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<OutboundModuleGridsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<OutboundOrderTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<PickBatchTypesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<StatusesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<UnitOfMeasurementConversionsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<UnitsOfMeasurementDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<AddressesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<BusinessPartnersDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<CarriersDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<CarrierServicesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<CompaniesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<CountriesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<CountryLocationsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<CountrySubDivisionsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<CurrenciesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<FacilitiesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<FacilityAisleFacesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<FacilityFloorsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<FacilityWorkAreasDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<FacilityZonesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<GalaxiesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InventoryLocationsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InventoryLocationSizesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InventoryLocationsSlottingDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<LanguagesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MaterialHandlingUnitConfigurationsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MaterialsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MeasurementSystemsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<PeopleDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<PlanetarySystemsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<PlanetRegionsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<PlanetsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<PlanetSubRegionsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<UniversesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<DocumentsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<HandlingUnitsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<HandlingUnitsShippingDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InboundOrderLinesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InboundOrdersDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InventoryUnitsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<InventoryUnitTransactionsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<MoveQueuesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<OutboundCarrierManifestPickupsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<OutboundCarrierManifestsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<OutboundOrderLinesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<OutboundOrderPackingDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<OutboundOrdersDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<OutboundShipmentsDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<PickBatchesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddDbContext<ReceivingDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
			services.AddTransient<IAisleFaceStorageTypesRepository, AisleFaceStorageTypesRepository>();
			services.AddTransient<IAssemblyModuleGridsRepository, AssemblyModuleGridsRepository>();
			services.AddTransient<IBaySequenceTypesRepository, BaySequenceTypesRepository>();
			services.AddTransient<IBusinessPartnerTypesRepository, BusinessPartnerTypesRepository>();
			services.AddTransient<ICarrierTypesRepository, CarrierTypesRepository>();
			services.AddTransient<ICommunicationMediumsRepository, CommunicationMediumsRepository>();
			services.AddTransient<IContactFunctionsRepository, ContactFunctionsRepository>();
			services.AddTransient<ICurrencyTypesRepository, CurrencyTypesRepository>();
			services.AddTransient<IDateTimePeriodFormatsRepository, DateTimePeriodFormatsRepository>();
			services.AddTransient<IDateTimePeriodFunctionsRepository, DateTimePeriodFunctionsRepository>();
			services.AddTransient<IDocumentMessageTypesRepository, DocumentMessageTypesRepository>();
			services.AddTransient<IExecutionModuleGridsRepository, ExecutionModuleGridsRepository>();
			services.AddTransient<IFoundationModuleGridsRepository, FoundationModuleGridsRepository>();
			services.AddTransient<IHandlingUnitTypesRepository, HandlingUnitTypesRepository>();
			services.AddTransient<IInboundModuleGridsRepository, InboundModuleGridsRepository>();
			services.AddTransient<IInboundOrderTypesRepository, InboundOrderTypesRepository>();
			services.AddTransient<IInventoryModuleGridsRepository, InventoryModuleGridsRepository>();
			services.AddTransient<IInventoryStatesRepository, InventoryStatesRepository>();
			services.AddTransient<IInventoryUnitTransactionContextsRepository, InventoryUnitTransactionContextsRepository>();
			services.AddTransient<ILocationFunctionsRepository, LocationFunctionsRepository>();
			services.AddTransient<ILogicalOrientationsRepository, LogicalOrientationsRepository>();
			services.AddTransient<IMaterialTypesRepository, MaterialTypesRepository>();
			services.AddTransient<IMeasurementUnitsOfRepository, MeasurementUnitsOfRepository>();
			services.AddTransient<IMessageFunctionsRepository, MessageFunctionsRepository>();
			services.AddTransient<IMessageResponseTypesRepository, MessageResponseTypesRepository>();
			services.AddTransient<IMonetaryAmountTypesRepository, MonetaryAmountTypesRepository>();
			services.AddTransient<IMoveQueueContextsRepository, MoveQueueContextsRepository>();
			services.AddTransient<IMoveQueueTypesRepository, MoveQueueTypesRepository>();
			services.AddTransient<INetworkModuleGridsRepository, NetworkModuleGridsRepository>();
			services.AddTransient<IOutboundModuleGridsRepository, OutboundModuleGridsRepository>();
			services.AddTransient<IOutboundOrderTypesRepository, OutboundOrderTypesRepository>();
			services.AddTransient<IPickBatchTypesRepository, PickBatchTypesRepository>();
			services.AddTransient<IStatusesRepository, StatusesRepository>();
			services.AddTransient<IUnitOfMeasurementConversionsRepository, UnitOfMeasurementConversionsRepository>();
			services.AddTransient<IUnitsOfMeasurementRepository, UnitsOfMeasurementRepository>();
			services.AddTransient<IAddressesRepository, AddressesRepository>();
			services.AddTransient<IBusinessPartnersRepository, BusinessPartnersRepository>();
			services.AddTransient<ICarriersRepository, CarriersRepository>();
			services.AddTransient<ICarrierServicesRepository, CarrierServicesRepository>();
			services.AddTransient<ICompaniesRepository, CompaniesRepository>();
			services.AddTransient<ICountriesRepository, CountriesRepository>();
			services.AddTransient<ICountryLocationsRepository, CountryLocationsRepository>();
			services.AddTransient<ICountrySubDivisionsRepository, CountrySubDivisionsRepository>();
			services.AddTransient<ICurrenciesRepository, CurrenciesRepository>();
			services.AddTransient<IFacilitiesRepository, FacilitiesRepository>();
			services.AddTransient<IFacilityAisleFacesRepository, FacilityAisleFacesRepository>();
			services.AddTransient<IFacilityFloorsRepository, FacilityFloorsRepository>();
			services.AddTransient<IFacilityWorkAreasRepository, FacilityWorkAreasRepository>();
			services.AddTransient<IFacilityZonesRepository, FacilityZonesRepository>();
			services.AddTransient<IGalaxiesRepository, GalaxiesRepository>();
			services.AddTransient<IInventoryLocationsRepository, InventoryLocationsRepository>();
			services.AddTransient<IInventoryLocationSizesRepository, InventoryLocationSizesRepository>();
			services.AddTransient<IInventoryLocationsSlottingRepository, InventoryLocationsSlottingRepository>();
			services.AddTransient<ILanguagesRepository, LanguagesRepository>();
			services.AddTransient<IMaterialHandlingUnitConfigurationsRepository, MaterialHandlingUnitConfigurationsRepository>();
			services.AddTransient<IMaterialsRepository, MaterialsRepository>();
			services.AddTransient<IMeasurementSystemsRepository, MeasurementSystemsRepository>();
			services.AddTransient<IPeopleRepository, PeopleRepository>();
			services.AddTransient<IPlanetarySystemsRepository, PlanetarySystemsRepository>();
			services.AddTransient<IPlanetRegionsRepository, PlanetRegionsRepository>();
			services.AddTransient<IPlanetsRepository, PlanetsRepository>();
			services.AddTransient<IPlanetSubRegionsRepository, PlanetSubRegionsRepository>();
			services.AddTransient<IUniversesRepository, UniversesRepository>();
			services.AddTransient<IDocumentsRepository, DocumentsRepository>();
			services.AddTransient<IHandlingUnitsRepository, HandlingUnitsRepository>();
			services.AddTransient<IHandlingUnitsShippingRepository, HandlingUnitsShippingRepository>();
			services.AddTransient<IInboundOrderLinesRepository, InboundOrderLinesRepository>();
			services.AddTransient<IInboundOrdersRepository, InboundOrdersRepository>();
			services.AddTransient<IInventoryUnitsRepository, InventoryUnitsRepository>();
			services.AddTransient<IInventoryUnitTransactionsRepository, InventoryUnitTransactionsRepository>();
			services.AddTransient<IMoveQueuesRepository, MoveQueuesRepository>();
			services.AddTransient<IOutboundCarrierManifestPickupsRepository, OutboundCarrierManifestPickupsRepository>();
			services.AddTransient<IOutboundCarrierManifestsRepository, OutboundCarrierManifestsRepository>();
			services.AddTransient<IOutboundOrderLinesRepository, OutboundOrderLinesRepository>();
			services.AddTransient<IOutboundOrderPackingRepository, OutboundOrderPackingRepository>();
			services.AddTransient<IOutboundOrdersRepository, OutboundOrdersRepository>();
			services.AddTransient<IOutboundShipmentsRepository, OutboundShipmentsRepository>();
			services.AddTransient<IPickBatchesRepository, PickBatchesRepository>();
			services.AddTransient<IReceivingRepository, ReceivingRepository>();
			services.AddTransient<IAisleFaceStorageTypesService, AisleFaceStorageTypesService>();
			services.AddTransient<IAssemblyModuleGridsService, AssemblyModuleGridsService>();
			services.AddTransient<IBaySequenceTypesService, BaySequenceTypesService>();
			services.AddTransient<IBusinessPartnerTypesService, BusinessPartnerTypesService>();
			services.AddTransient<ICarrierTypesService, CarrierTypesService>();
			services.AddTransient<ICommunicationMediumsService, CommunicationMediumsService>();
			services.AddTransient<IContactFunctionsService, ContactFunctionsService>();
			services.AddTransient<ICurrencyTypesService, CurrencyTypesService>();
			services.AddTransient<IDateTimePeriodFormatsService, DateTimePeriodFormatsService>();
			services.AddTransient<IDateTimePeriodFunctionsService, DateTimePeriodFunctionsService>();
			services.AddTransient<IDocumentMessageTypesService, DocumentMessageTypesService>();
			services.AddTransient<IExecutionModuleGridsService, ExecutionModuleGridsService>();
			services.AddTransient<IFoundationModuleGridsService, FoundationModuleGridsService>();
			services.AddTransient<IHandlingUnitTypesService, HandlingUnitTypesService>();
			services.AddTransient<IInboundModuleGridsService, InboundModuleGridsService>();
			services.AddTransient<IInboundOrderTypesService, InboundOrderTypesService>();
			services.AddTransient<IInventoryModuleGridsService, InventoryModuleGridsService>();
			services.AddTransient<IInventoryStatesService, InventoryStatesService>();
			services.AddTransient<IInventoryUnitTransactionContextsService, InventoryUnitTransactionContextsService>();
			services.AddTransient<ILocationFunctionsService, LocationFunctionsService>();
			services.AddTransient<ILogicalOrientationsService, LogicalOrientationsService>();
			services.AddTransient<IMaterialTypesService, MaterialTypesService>();
			services.AddTransient<IMeasurementUnitsOfService, MeasurementUnitsOfService>();
			services.AddTransient<IMessageFunctionsService, MessageFunctionsService>();
			services.AddTransient<IMessageResponseTypesService, MessageResponseTypesService>();
			services.AddTransient<IMonetaryAmountTypesService, MonetaryAmountTypesService>();
			services.AddTransient<IMoveQueueContextsService, MoveQueueContextsService>();
			services.AddTransient<IMoveQueueTypesService, MoveQueueTypesService>();
			services.AddTransient<INetworkModuleGridsService, NetworkModuleGridsService>();
			services.AddTransient<IOutboundModuleGridsService, OutboundModuleGridsService>();
			services.AddTransient<IOutboundOrderTypesService, OutboundOrderTypesService>();
			services.AddTransient<IPickBatchTypesService, PickBatchTypesService>();
			services.AddTransient<IStatusesService, StatusesService>();
			services.AddTransient<IUnitOfMeasurementConversionsService, UnitOfMeasurementConversionsService>();
			services.AddTransient<IUnitsOfMeasurementService, UnitsOfMeasurementService>();
			services.AddTransient<IAddressesService, AddressesService>();
			services.AddTransient<IBusinessPartnersService, BusinessPartnersService>();
			services.AddTransient<ICarriersService, CarriersService>();
			services.AddTransient<ICarrierServicesService, CarrierServicesService>();
			services.AddTransient<ICompaniesService, CompaniesService>();
			services.AddTransient<ICountriesService, CountriesService>();
			services.AddTransient<ICountryLocationsService, CountryLocationsService>();
			services.AddTransient<ICountrySubDivisionsService, CountrySubDivisionsService>();
			services.AddTransient<ICurrenciesService, CurrenciesService>();
			services.AddTransient<IFacilitiesService, FacilitiesService>();
			services.AddTransient<IFacilityAisleFacesService, FacilityAisleFacesService>();
			services.AddTransient<IFacilityFloorsService, FacilityFloorsService>();
			services.AddTransient<IFacilityWorkAreasService, FacilityWorkAreasService>();
			services.AddTransient<IFacilityZonesService, FacilityZonesService>();
			services.AddTransient<IGalaxiesService, GalaxiesService>();
			services.AddTransient<IInventoryLocationsService, InventoryLocationsService>();
			services.AddTransient<IInventoryLocationSizesService, InventoryLocationSizesService>();
			services.AddTransient<IInventoryLocationsSlottingService, InventoryLocationsSlottingService>();
			services.AddTransient<ILanguagesService, LanguagesService>();
			services.AddTransient<IMaterialHandlingUnitConfigurationsService, MaterialHandlingUnitConfigurationsService>();
			services.AddTransient<IMaterialsService, MaterialsService>();
			services.AddTransient<IMeasurementSystemsService, MeasurementSystemsService>();
			services.AddTransient<IPeopleService, PeopleService>();
			services.AddTransient<IPlanetarySystemsService, PlanetarySystemsService>();
			services.AddTransient<IPlanetRegionsService, PlanetRegionsService>();
			services.AddTransient<IPlanetsService, PlanetsService>();
			services.AddTransient<IPlanetSubRegionsService, PlanetSubRegionsService>();
			services.AddTransient<IUniversesService, UniversesService>();
			services.AddTransient<IDocumentsService, DocumentsService>();
			services.AddTransient<IHandlingUnitsService, HandlingUnitsService>();
			services.AddTransient<IHandlingUnitsShippingService, HandlingUnitsShippingService>();
			services.AddTransient<IInboundOrderLinesService, InboundOrderLinesService>();
			services.AddTransient<IInboundOrdersService, InboundOrdersService>();
			services.AddTransient<IInventoryUnitsService, InventoryUnitsService>();
			services.AddTransient<IInventoryUnitTransactionsService, InventoryUnitTransactionsService>();
			services.AddTransient<IMoveQueuesService, MoveQueuesService>();
			services.AddTransient<IOutboundCarrierManifestPickupsService, OutboundCarrierManifestPickupsService>();
			services.AddTransient<IOutboundCarrierManifestsService, OutboundCarrierManifestsService>();
			services.AddTransient<IOutboundOrderLinesService, OutboundOrderLinesService>();
			services.AddTransient<IOutboundOrderPackingService, OutboundOrderPackingService>();
			services.AddTransient<IOutboundOrdersService, OutboundOrdersService>();
			services.AddTransient<IOutboundShipmentsService, OutboundShipmentsService>();
			services.AddTransient<IPickBatchesService, PickBatchesService>();
			services.AddTransient<IReceivingService, ReceivingService>();
			services.AddTransient<AisleFaceStorageTypesPost>();
			services.AddTransient<AssemblyModuleGridsPost>();
			services.AddTransient<BaySequenceTypesPost>();
			services.AddTransient<BusinessPartnerTypesPost>();
			services.AddTransient<CarrierTypesPost>();
			services.AddTransient<CommunicationMediumsPost>();
			services.AddTransient<ContactFunctionsPost>();
			services.AddTransient<CurrencyTypesPost>();
			services.AddTransient<DateTimePeriodFormatsPost>();
			services.AddTransient<DateTimePeriodFunctionsPost>();
			services.AddTransient<DocumentMessageTypesPost>();
			services.AddTransient<ExecutionModuleGridsPost>();
			services.AddTransient<FoundationModuleGridsPost>();
			services.AddTransient<HandlingUnitTypesPost>();
			services.AddTransient<InboundModuleGridsPost>();
			services.AddTransient<InboundOrderTypesPost>();
			services.AddTransient<InventoryModuleGridsPost>();
			services.AddTransient<InventoryStatesPost>();
			services.AddTransient<InventoryUnitTransactionContextsPost>();
			services.AddTransient<LocationFunctionsPost>();
			services.AddTransient<LogicalOrientationsPost>();
			services.AddTransient<MaterialTypesPost>();
			services.AddTransient<MeasurementUnitsOfPost>();
			services.AddTransient<MessageFunctionsPost>();
			services.AddTransient<MessageResponseTypesPost>();
			services.AddTransient<MonetaryAmountTypesPost>();
			services.AddTransient<MoveQueueContextsPost>();
			services.AddTransient<MoveQueueTypesPost>();
			services.AddTransient<NetworkModuleGridsPost>();
			services.AddTransient<OutboundModuleGridsPost>();
			services.AddTransient<OutboundOrderTypesPost>();
			services.AddTransient<PickBatchTypesPost>();
			services.AddTransient<StatusesPost>();
			services.AddTransient<UnitOfMeasurementConversionsPost>();
			services.AddTransient<UnitsOfMeasurementPost>();
			services.AddTransient<AddressesPost>();
			services.AddTransient<BusinessPartnersPost>();
			services.AddTransient<CarriersPost>();
			services.AddTransient<CarrierServicesPost>();
			services.AddTransient<CompaniesPost>();
			services.AddTransient<CountriesPost>();
			services.AddTransient<CountryLocationsPost>();
			services.AddTransient<CountrySubDivisionsPost>();
			services.AddTransient<CurrenciesPost>();
			services.AddTransient<FacilitiesPost>();
			services.AddTransient<FacilityAisleFacesPost>();
			services.AddTransient<FacilityFloorsPost>();
			services.AddTransient<FacilityWorkAreasPost>();
			services.AddTransient<FacilityZonesPost>();
			services.AddTransient<GalaxiesPost>();
			services.AddTransient<InventoryLocationsPost>();
			services.AddTransient<InventoryLocationSizesPost>();
			services.AddTransient<InventoryLocationsSlottingPost>();
			services.AddTransient<LanguagesPost>();
			services.AddTransient<MaterialHandlingUnitConfigurationsPost>();
			services.AddTransient<MaterialsPost>();
			services.AddTransient<MeasurementSystemsPost>();
			services.AddTransient<PeoplePost>();
			services.AddTransient<PlanetarySystemsPost>();
			services.AddTransient<PlanetRegionsPost>();
			services.AddTransient<PlanetsPost>();
			services.AddTransient<PlanetSubRegionsPost>();
			services.AddTransient<UniversesPost>();
			services.AddTransient<DocumentsPost>();
			services.AddTransient<HandlingUnitsPost>();
			services.AddTransient<HandlingUnitsShippingPost>();
			services.AddTransient<InboundOrderLinesPost>();
			services.AddTransient<InboundOrdersPost>();
			services.AddTransient<InventoryUnitsPost>();
			services.AddTransient<InventoryUnitTransactionsPost>();
			services.AddTransient<MoveQueuesPost>();
			services.AddTransient<OutboundCarrierManifestPickupsPost>();
			services.AddTransient<OutboundCarrierManifestsPost>();
			services.AddTransient<OutboundOrderLinesPost>();
			services.AddTransient<OutboundOrderPackingPost>();
			services.AddTransient<OutboundOrdersPost>();
			services.AddTransient<OutboundShipmentsPost>();
			services.AddTransient<PickBatchesPost>();
			services.AddTransient<ReceivingPost>();

            services.AddDbContext<BotspielBotMessagesDB>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
            services.AddTransient<IBotspielBotMessagesRepository, BotspielBotMessagesRepository>();
            services.AddTransient<IBotspielBotMessagesService, BotspielBotMessagesService>();
            services.AddTransient<BotspielBotMessagesPost>();
            services.AddTransient<BotUserEntityContext>();
            services.AddSingleton<NavigationEntityData>();
            services.AddSingleton<IActionContextAccessor, ActionContextAccessor>();
            services.AddTransient<BotSpielBotAdapter>();
            //Custom Code Start | Added Code Block 
            services.AddTransient<Countries>();
            services.AddTransient<CountrySubDivisions>();
            services.AddScoped<SelectOptionStings>();
            services.AddScoped<CommonlyUsedSelects>();
            services.AddScoped<VolumeAndWeight>();
            services.AddTransient<IValidator<InventoryLocationsSlottingPost>, InventoryLocationsSlottingPostValidator>();
            services.AddTransient<IValidator<InventoryLocationsPost>, InventoryLocationsPostValidator>();
            services.AddTransient<IValidator<InventoryUnitsPost>, InventoryUnitsPostValidator>();
            //Custom Code End
        }
    }
}


 
